{
 "title": "OneAI",
 "description": "VM allocations based in previous day usage",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average CPU predicted usage per Host",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(one_host_id) (opennebula_vm_cpu_ratio)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average CPU predicted usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(opennebula_vm_predicted_cpu_usage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average CPU real usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(opennebula_vm_cpu_ratio)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Prediction Accuracy",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "(($B - abs($A - $B)) / $B) * 100",
     "type": "math"
    }
   ]
  },
  { "title": "Core optimization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "VMs per Host",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "count_values(\"count\", opennebula_vm_suggested_allocation{func=\"0\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VM allocation suggestion",
   "type": "table",
   "description": "VM allocation optimizing the number of cores in use (within each cluster)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "opennebula_vm_suggested_allocation{func=\"0\", is_change=\"True\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Load balancing optimization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "VMs per Host",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "count_values(\"count\", opennebula_vm_suggested_allocation{func=\"1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load balancing optimization",
   "type": "table",
   "description": "VM allocation optimizing the load balance (within each cluster)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "opennebula_vm_suggested_allocation{func=\"1\", is_change=\"True\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Migration optimization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "VMs per Host",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "count_values(\"count\", opennebula_vm_suggested_allocation{func=\"2\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Migration optimization",
   "type": "table",
   "description": "VM allocation optimizing the number of migrations (within each cluster)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "opennebula_vm_suggested_allocation{func=\"2\", is_change!=\"False\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}